# Generated by Django 4.0.4 on 2022-05-04 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bussed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=6, unique=True)),
                ('passenger', models.IntegerField(default=None)),
                ('security', models.IntegerField(choices=[(3, 'Max Level'), (1, 'Medium Level'), (0, 'Basic Level'), (2, 'High Level')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Companie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(default=None, max_length=250, unique=True)),
                ('phone', models.CharField(default=None, max_length=15, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('date_init', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('phone', models.CharField(default=None, max_length=15, unique=True)),
                ('email', models.EmailField(default=None, max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('avatar', models.FileField(default=None, null=True, upload_to='upload/')),
                ('permission', models.CharField(choices=[('U', 'User'), ('C', 'Client'), ('S', 'Sub-Client'), ('A', 'Administrator')], max_length=1)),
                ('session', models.IntegerField(choices=[(0, 'Offline'), (1, 'Online')])),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_schedule', models.CharField(max_length=8, unique=True)),
                ('check_out_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.bussed')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.companie')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.destination')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.origen')),
                ('sidewalks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.username')),
                ('code_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(default=None, max_length=250, unique=True)),
                ('phone', models.CharField(default=None, max_length=15, unique=True)),
                ('date_init', models.DateField(default=datetime.date.today)),
                ('age_job', models.IntegerField(default=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.companie')),
            ],
        ),
        migrations.CreateModel(
            name='CoDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('phone', models.CharField(default=None, max_length=15, unique=True)),
                ('date_init', models.DateField(default=datetime.date.today)),
                ('age_job', models.IntegerField(default=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.companie')),
            ],
        ),
        migrations.AddField(
            model_name='bussed',
            name='co_driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Api.codriver'),
        ),
        migrations.AddField(
            model_name='bussed',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.companie'),
        ),
        migrations.AddField(
            model_name='bussed',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.driver'),
        ),
    ]
