# Generated by Django 4.0.4 on 2022-04-26 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=250)),
                ('address', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[('1', 'Active'), ('0', 'Inactive')], default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Destinations',
            new_name='Destination',
        ),
        migrations.RenameModel(
            old_name='Origens',
            new_name='Origen',
        ),
        migrations.RenameModel(
            old_name='Platforms',
            new_name='Platform',
        ),
        migrations.RenameModel(
            old_name='Bus',
            new_name='Bussed',
        ),
        migrations.RenameModel(
            old_name='Drivers',
            new_name='Driver',
        ),
        migrations.AlterField(
            model_name='bussed',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.companie'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.companie'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.companie'),
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
