# Generated by Django 4.0.4 on 2022-05-01 04:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussed',
            name='model',
        ),
        migrations.AddField(
            model_name='bussed',
            name='passenger',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bussed',
            name='security',
            field=models.IntegerField(choices=[('', '')], default=0),
        ),
        migrations.AlterField(
            model_name='companie',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='access',
            field=models.IntegerField(choices=[(0, 'Invalid'), (1, 'Valid')], default=0),
        ),
        migrations.CreateModel(
            name='CoDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('phone', models.CharField(default=None, max_length=15, unique=True)),
                ('date_init', models.DateField(default=datetime.date.today)),
                ('age_job', models.IntegerField(default=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.companie')),
            ],
        ),
    ]
