# Generated by Django 4.0.4 on 2022-05-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='expirate_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='schedule',
            name='expirate_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='bussed',
            name='security',
            field=models.IntegerField(choices=[(1, 'Medium Level'), (0, 'Basic Level'), (2, 'High Level'), (3, 'Max Level')], default=0),
        ),
        migrations.AlterField(
            model_name='companie',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0),
        ),
    ]
