# Generated by Django 4.0.4 on 2022-05-04 13:55

from django.db import migrations, models
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_reserve_expirate_date_schedule_expirate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussed',
            name='security',
            field=models.IntegerField(choices=[(1, 'Medium Level'), (0, 'Basic Level'), (3, 'Max Level'), (2, 'High Level')], default=0),
        ),
        migrations.AlterField(
            model_name='username',
            name='password',
            field=mirage.fields.EncryptedCharField(max_length=250),
        ),
    ]
