# Generated by Django 4.0.4 on 2022-04-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_companie_rename_destinations_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companie',
            name='status',
            field=models.IntegerField(choices=[('0', 'Inactive'), ('1', 'Active')], default=0),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField()),
                ('access', models.IntegerField(choices=[('0', 'Invalid'), ('1', 'Valid')], default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.companie')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.username')),
            ],
        ),
    ]
