# Generated by Django 4.0.4 on 2022-05-01 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_bussed_model_bussed_passenger_bussed_security_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussed',
            name='co_driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Api.codriver'),
        ),
        migrations.AlterField(
            model_name='companie',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
    ]
