# Generated by Django 4.0.4 on 2022-04-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_username_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=250)),
                ('address', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[('1', 'Active'), ('0', 'Inactive')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='username',
            name='permission',
            field=models.CharField(choices=[('U', 'User'), ('C', 'Client'), ('S', 'Sub-Client'), ('A', 'Administrator')], max_length=1),
        ),
        migrations.AlterField(
            model_name='username',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='session',
            field=models.IntegerField(choices=[('0', 'Offline'), ('1', 'Online')], default=0),
        ),
    ]
