# Generated by Django 4.0.4 on 2022-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_companie_status_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='companie',
            name='status',
            field=models.IntegerField(choices=[('1', 'Active'), ('0', 'Inactive')], default=0),
        ),
    ]
