# Generated by Django 4.0.4 on 2022-05-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_bussed_security_alter_username_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='session',
        ),
        migrations.AddField(
            model_name='username',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=None),
        ),
        migrations.AlterField(
            model_name='bussed',
            name='security',
            field=models.IntegerField(choices=[(1, 'Medium Level'), (2, 'High Level'), (3, 'Max Level'), (0, 'Basic Level')], default=0),
        ),
    ]
