# Generated by Django 4.0.4 on 2022-05-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_bussed_co_driver_alter_companie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussed',
            name='security',
            field=models.IntegerField(choices=[(0, 'Basic Level'), (3, 'Max Level'), (2, 'High Level'), (1, 'Medium Level')], default=0),
        ),
        migrations.AlterField(
            model_name='companie',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='code_schedule',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
