# Generated by Django 4.0.4 on 2022-05-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_remove_username_session_username_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussed',
            name='security',
            field=models.IntegerField(choices=[(2, 'High Level'), (0, 'Basic Level'), (3, 'Max Level'), (1, 'Medium Level')], default=0),
        ),
        migrations.AlterField(
            model_name='username',
            name='last_name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='username',
            name='name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='username',
            name='password',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='username',
            name='permission',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Client'), (2, 'Sub-Client'), (3, 'Administrator')], default=0),
        ),
        migrations.AlterField(
            model_name='username',
            name='rut',
            field=models.CharField(default=None, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
    ]
