# Generated by Django 4.0.4 on 2022-04-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_rename_client_customer_alter_companie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='code_schedule',
            field=models.CharField(default=0, max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.username')),
                ('code_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.schedule')),
            ],
        ),
    ]
