# Generated by Django 4.0.4 on 2022-05-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_bussed_security_alter_companie_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default=None, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='companie',
            name='email',
            field=models.EmailField(default=None, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='email',
            field=models.EmailField(default=None, max_length=250, unique=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
