# Generated by Django 4.0.4 on 2022-04-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_schedule_code_schedule_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companie',
            name='status',
            field=models.IntegerField(choices=[('0', 'Inactive'), ('1', 'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='username',
            name='session',
            field=models.IntegerField(choices=[('0', 'Offline'), ('1', 'Online')]),
        ),
    ]
