# Generated by Django 4.0.4 on 2022-04-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_alter_companie_status_alter_username_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='avatar',
            field=models.FilePathField(default='avatar.png', path='./uploads/'),
        ),
        migrations.AlterField(
            model_name='username',
            name='session',
            field=models.IntegerField(choices=[(0, 'Offline'), (1, 'Online')]),
        ),
    ]
